name: Build shairport-sync-windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'START: Checkout repository'
        uses: actions/checkout@v4

      # --- FIX IMPLEMENTED HERE ---
      # Removed the 'winget install' command.
      # The runner already has Inno Setup; we just need to add it to the PATH.
      - name: 'START: Add Inno Setup to PATH'
        shell: pwsh
        run: |
          echo "--- Inno Setup is pre-installed. Adding to PATH... ---"
          echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "--- Inno Setup PATH set. ---"
      # --------------------------

      # --- Phase 1: Bonjour SDK Preparation ---
      - name: 'START: Download mDNSResponder libraries'
        shell: pwsh
        run: |
          echo "--- Starting Bonjour SDK preparation ---"
          echo "Downloading Bonjour SDK..."
          Invoke-WebRequest -Uri "https://github.com/leapbtw/Bonjour-SDK-Windows/archive/refs/tags/2.0.2.zip" -OutFile "bonjour.zip"
          echo "Extracting Bonjour SDK..."
          Expand-Archive -Path "bonjour.zip" -DestinationPath "."
          echo "Moving Bonjour SDK to mDNSResponder directory..."
          Move-Item -Path "Bonjour-SDK-Windows-2.0.2" -Destination "mDNSResponder"
          echo "--- Bonjour SDK preparation complete ---"

      - name: 'START: Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            base-devel
            mingw-64-x86_64-toolchain
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libconfig
            mingw-w64-x86_64-popt
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-libsoxr
            mingw-w64-x86_64-libao

      # --- Phase 1: Bonjour SDK Preparation ---
      - name: 'START: Download and Install Bonjour SDK'
        shell: pwsh
        run: |
          echo "--- Starting Bonjour SDK preparation ---"
          echo "Downloading Bonjour SDK Setup (Requires Authentication Cookies)..."
          
          # --- FIX IMPLEMENTED HERE ---
          # Define Headers as a HashTable
          $headers = @{
              "Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
              "Accept-Language" = "en-GB,en-US;q=0.9,en;q=0.8"
              "Cache-Control" = "no-cache"
              "Connection" = "keep-alive"
              # The long cookie string from your curl command (-b) goes here
              "Cookie" = "dssid2=075dd59c-ec75-4628-9896-d5210326a0ac; dssf=1; pxro=1; as_rumid=1731415048.634; geo=IN; s_fid=239B35EAE4AB749D-3FD807B5E8B64F4A; s_cc=true; dslang=GB-EN; site=GBR; acn01=fZrYpw3uoMHWKVvpyb2f3RF2LXBA6IOo+XJD8hO0ApOPNe68PmR9MyIACO6hWbMcWA==; myacinfo=DAWTKNV323952cf8084a204fb20ab2508441a07d02d38a86c26f9f55cb5dab1d46ab9329e2e8f432e01dadbb879d590717ce93665b7b85dc9e8c54148c12599811e9667945be435b981722549099c3e1d741612cb613c9aef212207c28e3811629f573cd862aae967eeb48529da86d607870d3e11ab7a713aa7108adab019fb9f978edc29987bd9bd8d48e4928f33a3b5f4d7e449db0d70774ad35e289b5a89906aadf599e21d95f2608919b86f21cfaebefbcc659579e83e35c38c27b10231e83aff2aa8aaba572e5b58d02ea6cafdc5b1b1524bc88aa11903b20d3f5a483953db1357a4adf31c37622ba707115f348fa1fc31e35750802cb65b8f11237edef6e2b704db2ba8ad7b1ea0dd5320008b88611fa69a01cf7821f1324061fe525aa9b2c7a2ad72d2001a74a59f1bed917a237af802ea9931799d47c7a9bd701ac0e429663137c6037113db9de08805bbcd22d077c5b464550df0a4babd9ecc747a8033a90d8282eb8d41643455583809bee3e9ec83867b27297cd87c75a40e5e0293d109e3cb22cb8a18285d6ec1409e51fe43729deb516f0ab39d1f20bdbbb627a8cc99eb119841ad45b8fe89e8b345b18a1085c1a2800ea6a77c2982b42d70bda8ad92ecf9f117c4e0b802b016395f27e1b46fc74c5b1749a8a9132a9f97189d311c465799859d42abcbb7159daad961282f25b620875585a47V3; aidshd=AY+Noh5N+NPOfsGl4WM1NDYxNTIyLWFjZjMtNGIwMC1iODJmLTE1MmM5ZWYxNGNlZkeyS4j8l5G8BOqS+8wflfX/dXI6XVB1GJXoukUnbQvTFSIyoFzMmFFFlFi/l9gAVOCgljPxfoyJ/J8skevGvc3h4+uYn4UMTs4ZGU/T7bQsDbcBSVY5JUjqlXrxSZOoPYfV/8fhlBKqUQBiQzg9h2LdijzXLLN2+aZ5s4FTU+kCITpcVv2nsIhxJm+mieqcqQGXLXW5dN12tE3SXzV3GbbLKIidtSCGo47SXBw037A/QTfiKyUPIiAmRNy9p5XCrYZWSFvn+XJxYBQtKUpPiPtMbqCmZgDXdXjNqwEkISRuCGQUb0yvMj0dlsONxiqCYzPHXL+44cMVLjbFbCiZxMdds5K+oUUwHvxRWZlWgQzlOTBpsRd0DrEyH8zuQgZpDcykibou7BhZ+IsXJyxc4iLy8cAZZUxshM6Jt5lrdFktZVtMOxLDCtUswr+klLx0peI16+QeZ1dSsVWDdNyQBYk30hxu1EI/HWvvDNxE21RHOovDWav2c2YpnHfFBA5icKJ5oo566FVGOVHBBRPgnkrjHSXR4CMMdigVQP+PSjVoVVYLGq96kcvfZvTC+PuAoMxCKNOI6BkNQsmJslz3fWUc4kOs2F7UfI5cxvqp4odK5J0iZQ7VluqiZEO0frdHSATfFU8D5g4GyAaCJhBypFt3mYYGcMoPK15khlYIlp1+umjlquOFTzAUX4FR5h4GyZ1xBtvz/wYhLAVH3peS1pa6GJhfQjBfl5sV85CxdfQ=; s_pathLength=developer^%^3D2^%^2C; DSESSIONID=m0155tsappimtarbs8gsunnk4bbjrmnh0f051vt9ju69bvehf7u; ADCDownloadAuth=8rKUabtU2aJJUR2dTc6i58HkXX5UW9N^%^2FI8R77E5R1uEMRH6QMeCoeksNZh4cV64Hqiyr0gfKm1Ft^%^0D^%^0AhUtOGlcHT^%^2FjuiPlG^%^2BPcVajl44Qf0BXNd1b7R^%^2Flap1Tk^%^2BTr4mrZOfV9B^%^2FrdOrv4D8Pg3iT47qWQqj^%^0D^%^0AROKiHVNPTPJ2nP8qEFvW9BRA^%^0D^%^0A; s_sq=^%^5B^%^5BB^%^5D^%^5D"
              "Pragma" = "no-cache"
              "Referer" = "https://developer.apple.com/"
              "Sec-Fetch-Dest" = "document"
              "Sec-Fetch-Mode" = "navigate"
              "Sec-Fetch-Site" = "same-site"
              "Sec-Fetch-User" = "?1"
              "Upgrade-Insecure-Requests" = "1"
              "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
              "sec-ch-ua" = "`"Google Chrome`";v=`"141`", `"Not?A_Brand`";v=`"8`", `"Chromium`";v=`"141`"" # Escaped quotes with backticks `
              "sec-ch-ua-mobile" = "?0"
              "sec-ch-ua-platform" = "`"Windows`"" # Escaped quotes with backticks `
          }
          
          # Use Invoke-WebRequest with the URI and Headers
          Invoke-WebRequest -Uri "https://download.developer.apple.com/Developer_Tools/bonjour_sdk_for_windows_v3.0/bonjoursdksetup.exe" -Headers $headers -OutFile "bonjoursdksetup.exe"
          # --------------------------

          echo "Installing Bonjour SDK silently..."
          Start-Process -FilePath ".\bonjoursdksetup.exe" -ArgumentList "/qn /norestart" -Wait -PassThru

          echo "Cleaning up installer..."
          Remove-Item -Path "bonjoursdksetup.exe" -Force

          echo "--- Bonjour SDK installation complete ---"

      # --- Phase 2: Python Tray Wrapper ---
      - name: 'START: Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'START: Install Python dependencies'
        run: |
          echo "--- Installing PyInstaller, pystray, and pillow... ---"
          pip install pyinstaller pystray pillow
          echo "--- Python dependencies installed ---"

      - name: 'START: Build the Python wrapper'
        run: |
          echo "--- Running PyInstaller... ---"
          pyinstaller --onefile --windowed --name shairport-sync-windows tray/tray.py
          # pyinstaller --onefile --windowed --icon=icon.ico --name shairport-sync-windows tray/tray.py
          # copy icon.ico dist\icon.ico
          echo "--- PyInstaller build complete ---"

      # --- Phase 3: Inno Setup Installer ---
      - name: 'START: Compile the installer with Inno Setup'
        shell: pwsh
        run: |
          echo "--- Running Inno Setup Compiler (iscc)... ---"
          iscc "inno-setup/script.iss"
          echo "--- Inno Setup compilation complete ---"

      # --- Upload Artifact ---
      - name: 'START: Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: shairport-sync-windows
          path: inno-setup/Output/shairport-sync-windows-setup.exe
